### ISSUE TITLE
Android: Thumbnail Function Crash - Crashes Entire App

### ISSUE THREAD

**Issue by danbunkr** [dragermrb/capacitor-plugin-video-editor#5]
In some instances I am getting this error on Android  which is specific to the `android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:355)` Line in the Android plugin. It seems to be throwing an exception which crashes my Capacitor app. Should these type of errors be caught and passed back up to the JS level so we could handle them in a try catch around the `thumbnail` method

```
E  Serious error executing plugin
                                                                                                    java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                                                    	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:310)
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:253)
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:355)
                                                                                                    	at com.whiteguru.capacitor.plugin.videoeditor.VideoEditorLitr.thumbnail(VideoEditorLitr.java:141)
                                                                                                    	at com.whiteguru.capacitor.plugin.videoeditor.VideoEditorPlugin.thumbnail(VideoEditorPlugin.java:165)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
               E  FATAL EXCEPTION: CapacitorPlugins
                                                                                               
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:772)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                                                    	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:310)
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:253)
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:355)
                                                                                                    	at com.whiteguru.capacitor.plugin.videoeditor.VideoEditorLitr.thumbnail(VideoEditorLitr.java:141)
                                                                                                    	at com.whiteguru.capacitor.plugin.videoeditor.VideoEditorPlugin.thumbnail(VideoEditorPlugin.java:165)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:763) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by dragermrb** [comment]
IOS version should not be affected by this issue.
